version: "3.3"

services:
  app:
    build: .
    environment:
      - DEBUG=1
      - APP_NAME=app
      - APP_COUNT=3
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - redis
  worker:
    build: .
    environment:
      - DEBUG=1
      - APP_NAME=worker
      - HEALTH_REFRESH=10
      - CHAIN_URL=https://github.com/eco-stake/chain-registry
      - CHAIN_BRANCH=cosmos-directory-dev
      - CHAIN_REFRESH=60
      - VALIDATOR_URL=https://github.com/eco-stake/validator-registry
      - VALIDATOR_BRANCH=master
      - VALIDATOR_REFRESH=300
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - redis
      - app
  redis:
    image: redislabs/rejson:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loadmodule /usr/lib/redis/modules/rejson.so --save 20 1 --loglevel warning
    volumes: 
      - redis_data:/data

volumes:
  node_modules:
  redis_data: