version: "3.3"

services:
  app:
    build: 
      context: .
      args:
        - REGISTRY_URL=https://github.com/eco-stake/chain-registry
        - REGISTRY_BRANCH=cosmos-directory-dev
        - REGISTRY_REFRESH=60
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
